name: "Danger JS"
on: [pull_request]

jobs:
build:
name: Danger JS
runs-on: MacOS-latest
steps:
- uses: actions/checkout@v1
- name: Danger
uses: danger/danger-js@9.1.6
env:
GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
